env:
  RUBY_VERSION: 2.7.5
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  DB_HOST: localhost
  DEVELOPER_EMAIL_ADDRESS: "basile.quinchon@gmail.com"
  NODE_VERSION: 14
name: Rails tests
on: [push]
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: gem install rubocop
      - name: Check code
        run: rubocop
  rspec-test:
    name: RSpec
    needs: rubocop-test
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:11
        ports: ['5432:5432']
        env:
          RAILS_ENV: test
          POSTGRES_HOST: ${{ env.DB_HOST }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'yarn'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install library for postgres
        run: sudo apt-get -yqq install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Install packages
        run: yarn install
      - name: Prepare database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: ${{ env.DB_HOST }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: basile_quinchon_refonte_test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          cp config/database.yml config/database.yml.ci
          bundle exec rails db:prepare
      - name: Run tests
        env:
          DEVELOPER_EMAIL_ADDRESS: ${{ env.DEVELOPER_EMAIL_ADDRESS }}
        run: bundle exec rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: rspec-test
    if: ${{ !contains(github.event.head_commit.message, '[skip_deploy]') && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "basile-quinchon-new" # Must be unique in Heroku
          heroku_email: "basile.quinchon@gmail.com"
          branch: main
